#!/usr/bin/env python3
"""Write seed_ledger.json: every source fetched by agent5, sha256 of the fetched bytes, read_in_full, contribution, facts with locators."""
import hashlib, json, os
ROOT = os.path.abspath(os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))
S = os.path.join(ROOT, "sources")
def h(f): return hashlib.sha256(open(os.path.join(S, f), "rb").read()).hexdigest()
def seed(id_, ident, raw, txt, full, contribution, facts, note=""):
    return {"id": id_, "identifier": ident, "raw_file": "sources/" + raw, "raw_sha256": h(raw), "text_file": "sources/" + txt,
            "fetched": "2026-09-16", "read_in_full": full, "contribution": contribution, "facts": facts, "note": note}
F = lambda fact, loc: {"fact": fact, "locator": loc}
seeds = [
 seed("fremling2020", "arXiv:1910.12973v1 (Fremling et al., ZTF BTS I)", "1910.12973.pdf", "1910.12973.txt", True, "k corroboration, 2018 filter candidates, peakt zero point, SEDM exposure cost",
  [F("5-15 SN candidates per night assigned for spectroscopic follow-up (2018); strongly weather dependent", "section 2.2 lines 258-265, footnote 9 lines 308-311"),
   F("a few hundred alerts per night passed the 2018 BTS filter", "section 2.2 line 219"),
   F("SEDM capable of classifying >10 SNe in the 18.5-19 mag range every night", "section 1 lines 135-137"),
   F("typical SEDM exposure 1800 s at m about 18.5", "section 2.3 lines 336-337"),
   F("JD0 = JD - 2,458,000 for times of maximum", "Table 1 note d line 476"),
   F("761 SNe classified 2018 Apr 1 - Dec 31; 503 with SEDM", "section 3.2 lines 422-427"),
   F("ePESSTO agreement on 24 of 26 common sources", "section 3.2 lines 573-588")]),
 seed("perley2020", "arXiv:2009.01242v2 (Perley et al., ZTF BTS II)", "2009.01242.pdf", "2009.01242.txt", True, "k corroboration, candidate counts by filter version, peakt zero point",
  [F("typically 5-10 candidates saved on an average clear night", "section 2.1 lines 147-148"),
   F("first-year filter reduced ~10^6 alert packets per night to ~500 viable candidates; 2019 filter reduced false positives from several hundred per night to <=50", "section 2.1 lines 133-137, 159-161"),
   F("3147 spectroscopically classified transients in 25.5 months", "section 3 lines 477-478"),
   F("observed peak time axis in JD-2458000", "Figure 13 line 1952")],
  note="reference list (lines 1445-1660) scanned, not read line by line"),
 seed("blagorodnova2018", "arXiv:1710.02917v2 (Blagorodnova et al., SED Machine)", "1710.02917.pdf", "1710.02917.txt", True, "k corroboration (capacity)",
  [F("the dozen or so spectroscopic targets for SEDM are specified on a nightly basis", "section 6 line 1046"),
   F("average rate of 10 spectra per night", "section 7 line 1076"),
   F("1660 objects observed in 10 months, 465 iPTF transients", "section 6 lines 1039-1042")]),
 seed("fremling2021", "arXiv:2104.12980v2 (Fremling et al., SNIascore)", "2104.12980.pdf", "2104.12980.txt", True, "delta candidate (adjacent referent); tool-card threshold disagreement",
  [F("TPR 0.90 (SNIascore) versus 0.53 (SNID) at FPR < 1% on BTS18 validation", "Table 2 lines 387-407"),
   F("BTS18 validation: 1,016 spectra of 648 SNe", "section 2 lines 190-196"),
   F("FPR < 1% is a hard requirement for autonomous classification", "section 4.1 lines 298-299"),
   F("deployed 2021 April 15; TNS reports initially use threshold 0.9, not the recommended 0.6 or 0.8 cuts", "section 7 lines 523-546")]),
 seed("rehemtulla2024", "arXiv:2401.15167v1 (Rehemtulla et al., ZTF BTS III BTSbot)", "2401.15167.pdf", "2401.15167.txt", True, "k (primary), candidates per round, chance, delta prior (primary), replay cases",
  [F("~50 new candidate BTS sources per night, ~7 new real bright transients", "section 1 lines 94-95"),
   F("scanners saved 266 and sent SEDM IFU requests for 327 unique sources (11 non-extragalactic) with 2460175.5 < JD < 2460216.5", "section 4.1 lines 757-766"),
   F("the window is 41 nights; 184 sources satisfied bts_p1, median ~4.5 per night", "section 4.2 lines 953-958"),
   F("present-day window: 4,031 alerts from 251 bright transients and 15,159 alerts from 1,652 non-bright transients", "section 4.2 lines 898-902"),
   F("bts_p2 purity MM-CNN 93.0%, NN 91.2%, UM-CNN 92.5% on the test split; 'even small boosts in purity are valuable'", "Appendix B Table 6 lines 1323-1335, lines 1360-1364"),
   F("scanner triggering purity stated as 96.7% and as 95.6% in the same section", "lines 765-766 and line 806"),
   F("test split 512 bright-transient sources, 1,489 others", "Figure 4 line 420"),
   F("BTSbot v1.0 ran in production in October 2023; the paper's model is v1.0.1", "footnote 17 lines 1019-1023"),
   F("initial training queries: 19,735 sources, 1,115,395 alerts", "Table 1 line 276")]),
 seed("frohmaier2025", "arXiv:2501.16311v2 (Frohmaier et al., TiDES on 4MOST; arXiv id verified by arXiv API query ti:TiDES AND au:Frohmaier)", "2501.16311.pdf", "2501.16311.txt", True, "Rubin-era capacity; disagreement that TiDES is not a k-of-n selection",
  [F(">30,000 live transients over 5 years, ~250,000 fibre-hours", "abstract lines 40-46, section 1 line 105"),
   F("TiDES averages 30-35 LRS fibres per pointing", "section 2 lines 138-140"),
   F("TiDES cannot operate target-of-opportunity; has access to sufficient fibres to observe all live transients in a field", "section 3.4-3.5 lines 559-565"),
   F("~12 live transients per 4MOST field pass selection in well-sampled LSST fields", "footnote 20 line 630"),
   F("at best ~3% of LSST SNe Ia observed in a redshift bin", "Figure 9 caption line 1074")],
  note="figures and reference list scanned"),
 seed("claudi2018", "arXiv:1812.07401v1 (Claudi et al., SOXS)", "1812.07401.pdf", "1812.07401.txt", True, "zero contribution to k: no per-night target count stated",
  [F("SOXS consortium remunerated with 900 NTT nights over 5 years", "section 1 line 126"),
   F("PESSTO 150 nights per year; ePESSTO 200 nights over two years", "section 1 lines 94-95"),
   F("online pipeline sized for one typical night of 15-30 min exposures", "TLR_09 line 392")]),
 seed("leoni2022", "arXiv:2111.11438v2 (Leoni et al., Fink early SN Ia)", "2111.11438.pdf", "2111.11438.txt", True, "delta candidate (population FAIL); internal count disagreement",
  [F("uncertainty sampling efficiency 0.54 vs random 0.24, purity 0.89 vs 0.87", "Table 2 lines 437-460"),
   F("test sample reported as 23,530 (abstract), 23,425 (section 4) and 23,465 (section 6) alerts", "lines 40, 540, 679"),
   F("809 early SN Ia candidates reported Nov 2020 - Oct 2021; 535 spectroscopically classified, 459 (86%) SNe Ia", "section 5 lines 580-585")]),
 seed("bts_explorer_info", "https://sites.astro.caltech.edu/ztf/bts/explorer_info.html", "bts_explorer_info.html", "bts_explorer_info.txt", True, "peakt zero point (documented)",
  [F("column 'time': Time of peak, expressed as JD-2458000", "line 102"),
   F("quality cut includes objects which peaked after 2018 May 1st", "lines 15-16"),
   F("Saved date column exists in the explorer but not in the local CSV", "lines 51-52, 94-95")]),
 seed("anthropic_models_overview", "https://platform.claude.com/docs/en/models/overview (redirect target of docs.claude.com)", "anthropic_models_overview.html", "anthropic_models_overview.txt", True, "subject set",
  [F("current models Claude Fable 5.1, Opus 5, Sonnet 5, Haiku 4.5; reliable knowledge cutoff Jun 2026, May 2026, Jan 2026, Feb 2025", "lines 37-40, 77-81")]),
 seed("anthropic_transparency", "https://www.anthropic.com/transparency (Model Report dated August 17, 2026)", "anthropic_transparency.html", "anthropic_transparency.txt", False, "subject set cutoffs for Opus 5 and Sonnet 5; absence of Fable 5.1",
  [F("Claude Opus 5 knowledge cutoff May 2026", "lines 41-42"), F("Claude Sonnet 5 knowledge cutoff January 2026", "lines 88-89"),
   F("model list contains Claude Fable 5 but not Fable 5.1", "line 20")],
  note="read lines 1-180 (Opus 5, Sonnet 5, Fable 5 sections); sections for older models not read. Blocks nothing used here: only the three sections read enter the ledger"),
 seed("openai_models", "https://developers.openai.com/api/docs/models (redirect target of platform.openai.com/docs/models)", "openai_models.html", "openai_models.txt", True, "subject set",
  [F("GPT-6 Astra knowledge cutoff Apr 30, 2026", "lines 658-674"), F("GPT-5.6 Sol, Terra, Luna knowledge cutoff Feb 16, 2026", "lines 676-731")],
  note="lines 1-650 are site navigation"),
 seed("openai_gpt-6-astra", "https://developers.openai.com/api/docs/models/gpt-6-astra", "openai_gpt-6-astra.html", "openai_gpt-6-astra.txt", False, "corroborates GPT-6 Astra cutoff",
  [F("Apr 30, 2026 knowledge cutoff", "line 673")], note="searched for cutoff only; the models page read in full carries the same value"),
 seed("google_gemini_models", "https://ai.google.dev/gemini-api/docs/models", "google_gemini_models.html", "google_gemini_models.txt", True, "subject set availability (no cutoffs on this page)",
  [F("Gemini 3.8 Flash stable; Gemini 3.1 Pro preview", "lines 187-242")]),
 seed("google_gemini-3.8-flash", "https://ai.google.dev/gemini-api/docs/models/gemini-3.8-flash", "google_gemini-3.8-flash.html", "google_gemini-3.8-flash.txt", True, "zero contribution to cutoff ('Latest update' is not a cutoff)",
  [F("Latest update September 2026", "lines 242-243")]),
 seed("google_gemini-3.1-pro-preview", "https://ai.google.dev/gemini-api/docs/models/gemini-3.1-pro-preview", "google_gemini-3.1-pro-preview.html", "google_gemini-3.1-pro-preview.txt", True, "zero contribution to cutoff",
  [F("Latest update February 2026", "lines 244-245")]),
 seed("deepmind_card_3.8_flash", "https://deepmind.google/models/model-cards/gemini-3-8-flash/", "deepmind_modelcard_gemini-3-8-flash.html", "deepmind_modelcard_gemini-3-8-flash.txt", True, "subject set cutoff",
  [F("knowledge cutoff March 2026; some domains limited to January 2025", "line 352")]),
 seed("deepmind_card_3.7_flash", "https://deepmind.google/models/model-cards/gemini-3-7-flash/", "deepmind_modelcard_gemini-3-7-flash.html", "deepmind_modelcard_gemini-3-7-flash.txt", False, "none used (3.7 Flash not in subject set)",
  [F("knowledge cutoff March 2026; some domains January 2025", "line 371")], note="searched only"),
 seed("deepmind_card_3.1_pro", "https://deepmind.google/models/model-cards/gemini-3-1-pro/", "deepmind_modelcard_gemini-3-1-pro.html", "deepmind_modelcard_gemini-3-1-pro.txt", False, "absence of a cutoff statement (by search)",
  [F("training dataset deferred to the Gemini 3 Pro card", "line 197")], note="searched for cutoff; Gemini 3.1 Pro cutoff recorded UNDEMONSTRATED, so no decision rests on this partial read"),
 seed("deepmind_card_3_pro", "https://deepmind.google/models/model-cards/gemini-3-pro/", "deepmind_modelcard_gemini-3-pro.html", "deepmind_modelcard_gemini-3-pro.txt", False, "zero contribution",
  [], note="4,972 extracted lines; searched for 'cutoff' and 'knowledge is limited' with no hit; not read in full; blocks the Gemini 3.1 Pro cutoff, which stays UNDEMONSTRATED"),
]
led = {"agent": "agent5_resolution_replay", "seeds": seeds,
       "searches_without_a_seed": ["arXiv API abs:ePESSTO+ returned no ePESSTO+ survey paper (top hits 2602.03638, 2602.13036, 2503.21874, none about ePESSTO+ operations)"],
       "not_verified": ["PANEL_BRIEF.md rule 10 dates (Rubin alerts to brokers February 2026; LSST start 2026-06-30): not verified by agent5 and not used in any agent5 number"],
       "completeness": "20 sources fetched; 14 read in full, 6 partially with the partial reads named and no decision resting on their unread parts; inventory, not a completeness claim"}
json.dump(led, open(os.path.join(ROOT, "seed_ledger.json"), "w"), indent=2)
print(len(seeds), "seeds")
