#!/usr/bin/env python3
import os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from common import *  # noqa
S = [
 ("astronomy/wave2/PANEL_BRIEF_WAVE2.md", True, "PI D5 decisions (lines 12-18), agent 3 assignment, coordinator preamble items 1-3; hash verified"),
 ("astronomy/wave3/PANEL_BRIEF_WAVE3.md", True, "PI rulings 1-6, agent 3 assignment, preamble items 1-5; hash verified"),
 ("astronomy/PANEL_BRIEF.md", True, "rules 1-10 and deliverable formats"),
 ("astronomy/SYNTHESIS.md", True, "wave-1 slot table, disagreements (section 8), P4 refusal reasons"),
 ("fm-advantage-benchmark/SKILL.md", True, "stages, global refusals 1-16"),
 ("fm-advantage-benchmark/references/manifest.md", True, "slot definitions, D5 supplied inputs, ratification checks"),
 ("fm-advantage-benchmark/references/provenance.md", True, "five provenance fields"),
 ("fm-advantage-benchmark/references/stages/discovery.md", True, "D4 and D5 contract; D2 rule-change invalidation"),
 ("fm-advantage-benchmark/references/graph.md", True, "D5->R1 and R1->I1 edges"),
 ("fm-advantage-benchmark/schemas/domain_manifest.schema.json", True, "required slots, status enum, override_reason"),
 ("fm-advantage-benchmark/scripts/validate.py", True, "domain_manifest and axis_ledger checks"),
 ("astronomy/agent1_supply_corpus/cut_curve.json", True, "tau slot value and provenance"),
 ("astronomy/agent1_supply_corpus/corpus_ledger.json", False, "keys, inclusion rules, amendments, coverage read; exclusion ledger and seed facts skimmed (first 1,500 chars per key); blocks nothing in the manifest (tau and counts come from cut_curve.json)"),
 ("astronomy/agent3_labels_exposure/label_source_slot.json", True, "superseded label slot (class-level shares carried)"),
 ("astronomy/agent3_labels_exposure/exposure_key_slot.json", True, "exposure_key slot, subject cutoff table"),
 ("astronomy/agent4_tools_instrument/tool_inventory_slot.json", True, "tool_inventory slot; per-tool fields, summary, condition details"),
 ("astronomy/agent4_tools_instrument/REPORT.md", False, "lines 1-140 read (headline, sections 1-4); remapping proposal cause at lines 22-25 and 85; sections 5-8 not needed"),
 ("astronomy/agent5_resolution_replay/k_slot.json", True, "k slot"),
 ("astronomy/agent5_resolution_replay/delta_slot.json", True, "delta prior slot"),
 ("astronomy/agent5_resolution_replay/subject_set_slot.json", True, "subject_set slot"),
 ("astronomy/agent5_resolution_replay/d5_inputs.json", True, "budget, cost of action, S records and cell definition"),
 ("astronomy/agent5_resolution_replay/REPORT.md", False, "grep for delta resolution warning (line 48) only"),
 ("astronomy/agent2_floor_headroom/REPORT.md", False, "grep for tier AUC table lines 73-77 only (decision_epoch adjudicator)"),
 ("astronomy/wave2/agent1_rubin_bands/bands_FROZEN.md", True, "frozen bands, preconditions, strata, anti-widening; hash verified"),
 ("astronomy/wave2/agent1_rubin_bands/axis_ledger_rubin.json", True, "wave-2 axis state"),
 ("astronomy/wave2/agent1_rubin_bands/order_of_operations.log", True, "band hash time 18:51:26.922781Z"),
 ("astronomy/wave2/agent1_rubin_bands/amendments.md", True, "AM1-AM5 (procedure only)"),
 ("astronomy/wave2/agent1_rubin_bands/REPORT.md", True, "wave-2 cohort and P4 state"),
 ("astronomy/wave2/agent2_label_source/label_source_slot.json", True, "label_source slot for v1"),
 ("astronomy/wave2/agent2_label_source/REPORT.md", True, "bounds, disagreements (TNS discovery date proxy)"),
 ("astronomy/wave2/agent4_instrument/compositions_FROZEN.md", True, "decision epoch operationalisation E1/E3; hash verified"),
 ("astronomy/wave2/agent4_instrument/r1_spec.md", True, "R1 cap (3 cells); hash verified"),
 ("astronomy/wave2/agent4_instrument/REPORT.md", True, "PRE-I1 calibration, chance disagreement, tool defects"),
 ("astronomy/wave2/agent4_instrument/AMENDMENTS.md", True, "A-1..A-3 (not manifest-level)"),
 ("astronomy/wave2/agent5_skill_maintenance/REPORT.md", True, "transfer BLOCKED, issues"),
 ("astronomy/wave2/agent5_skill_maintenance/transfer_record.json", False, "first 80 lines (status, package); remainder not needed"),
 ("astronomy/wave3/agent1_cohort_finish/REPORT.md", True, "cohort counts, PPDB, delta 0.05 planning thresholds"),
 ("astronomy/wave3/agent1_cohort_finish/axis_ledger_rubin_v2.json", True, "axes carried into axis_ledger_v2_against_frozen_bands.json"),
 ("astronomy/wave3/agent1_cohort_finish/rubin_cohort_count.json", True, "w3-01..w3-09 values"),
 ("astronomy/wave3/agent1_cohort_finish/order_of_operations.log", True, "count protocol and seal times/hashes"),
 ("astronomy/wave3/agent1_cohort_finish/amendments_w3.md", True, "AM6, AM7"),
 ("astronomy/wave3/agent4_tool_recount/REPORT.md", True, "recount dispositions, qualifier, disagreements"),
 ("astronomy/wave3/agent4_tool_recount/tool_coverage_axis.json", False, "top-level fields and per_tool dispositions read programmatically; per-tool error strings not all read"),
 ("astronomy/wave3/agent4_tool_recount/run_log.jsonl", True, "198 rows parsed for timestamps, statuses, voided runs"),
 ("astronomy/wave3/agent4_tool_recount/order_of_operations.log", True, "protocol, seal, run_log and axis hashes"),
 ("astronomy/wave3/agent4_tool_recount/power_calibration_delta005.json", True, "delta 0.05 and 0.018 calibration table"),
 ("astronomy/wave3/agent4_tool_recount/recount_protocol_FROZEN.md", False, "grep for remapping section 2 (lines 28-44)"),
 ("astronomy/wave3/agent4_tool_recount/sealed/alert_ids_SEALED_v2.json", False, "first 40 lines (rule, accepted ids)"),
 ("astronomy/wave3/agent5_integrity/REPORT.md", True, "transfer PENDING_RECEIPT, replay cases"),
 ("astronomy/wave3/agent5_integrity/transfer_record.json", False, "first 60 lines (status, receipt_hash, holder, package head)"),
]
seeds = []
for p, full, c in S:
    seeds.append({"id": os.path.basename(p), "file": p, "sha256": sha(p), "read_in_full": full, "contribution": c})
dump({"agent": "wave3/agent3_manifest_freeze", "date": "2026-09-16", "seeds": seeds,
      "not_read": ["astronomy/wave3/agent2_measured_labels/* (running; listed only)", "RULINGS_SEALED.csv (never opened)"],
      "completeness": f"{len(seeds)} files; {sum(s['read_in_full'] for s in seeds)} read in full; partial reads name the part used and block nothing in the manifest"},
     f"{OUT}/seed_ledger.json")
